name: Deploy Backend to Render

on:
    push:
        paths:
            - "server/**"
            - ".github/workflows/cd-backend.yaml"

jobs:
    deploy:
        name: Deploy Backend
        runs-on: ubuntu-latest

        steps:
            - name: Trigger Render Deploy Hook
              run: |
                  curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
